# build_push_docker:
#   stage: build
#   image:
#     name: gcr.io/kaniko-project/executor:v1.8.0-debug
#     entrypoint: ['']
#   script:
#     - /kaniko/executor
#       --context "${CI_PROJECT_DIR}"
#       --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
#       --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
#       --insecure

# build_push_docker:
#   image: docker:20.10.16
#   stage: build
#   services:
#     - name: docker:20-dind
#       alias: docker
#       command: ['--tls=false']
#   variables:
#     IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
#     DOCKER_TLS_CERTDIR: ''
#     DOCKER_DRIVER: overlay2
#     DOCKER_HOST: 'tcp://docker:2375'
#   script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - docker build -t $IMAGE_TAG .
#     - docker push $IMAGE_TAG
