building_energy_data:
  image: python:3.11
  stage: build
  only:
    - schedules
    - web
  before_script:
    - git clone https://gitlab.opencode.de/smart-city-muenster/klimadashboard-muenster/ms-buildings-parser.git
    - pip install -r ms-buildings-parser/requirements.txt
  script:
    - python ms-buildings-parser/index.py assets/data
    - git config user.email "f.erdmann@reedu.de"
    - git config user.name "ci-bot"
    - git remote remove gitlab_ci_origin || true # Local repo state may be cached
    - git remote add gitlab_ci_origin https://oauth2:$ACCESS_TOKEN@gitlab.opencode.de/smart-city-muenster/klimadashboard-muenster/klimadashboard-muenster.git
    - git add assets/*
    - "git commit -m 'ci: update buildings energy data'"
    - git push -f gitlab_ci_origin HEAD:main
