default:
  image: node:16.16.0

deploy_preview:
  stages:
    - deploy
  except:
    - main
  script:
    - npm install --location=global vercel
    - npx next telemetry disable
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN

deploy_production:
  stages:
    - deploy
  only:
    - main
  script:
    - npm install --location=global vercel
    - npx next telemetry disable
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
